function [all_profiles,profile_names] = saved_profiles()
% Here are the supported models with some default settings:
%
% p.model_settings = struct(...
%     'model_type', "lrm",...
%     'alpha', 0.5,...
%     'cv_spec', 5,...
%     'max_iterations', 1e8);
%
% p.model_settings = struct(...
%     'model_type', "tree",...
%     'num_trees', 100);
%
% p.model_settings = struct(...
%     'model_type', "nn-mlp",...
%     'cv_spec', 5,...
%     'max_fail', 6,...
%     'min_grad', 1e-7,...
%     'hidden_neurons', 64,...
%     'backprop_func', 'trainscg',...
%     'L2_regularization', 1e-4,...
%     'max_epochs', 200);
%
% p.model_settings = struct(...
%     'model_type', "nn-cnn1d",...
%     'cv_spec', 5,...
%     'max_epochs', 500,...
%     'num_filters', 64,...
%     'learning_rate', 1e-2);

% Initialize cell array of profiles
all_profiles = cell(0);
profile_names = cell(0);

%% PROFILE 1
profile_name = "Human, R/H - ROC Curve";
p = struct;
p.primary_var = "frequency_limit";
p.primary_vals = [];
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', []);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 10, ...
    'frequency_limit', 30, ...
    'training_type', "percentage", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'bolus_type', "BB")
    struct('signal_sel', "raw_signal", 'bolus_type', "AB")
    struct('signal_sel', "IPFM_signal", 'bolus_type', "BB")
    struct('signal_sel', "IPFM_signal", 'bolus_type', "AB")
    struct('signal_sel', "EHR_signal", 'bolus_type', "BB")
    struct('signal_sel', "EHR_signal", 'bolus_type', "AB")
    };
p.legend_vec = {
    "Raw PVP, BB"
    "Raw PVP, AB"
    "IPFM-PVP, BB"
    "IPFM-PVP, AB"
    "IPFM-HB, BB"
    "IPFM-HB, AB"
    };
p.line_styles = {
    "-o"
    % "--o"
    "-x"
    % "--x"
    "-v"
    % "--v"
    };
p.line_colors = {
    "#FF0000"
    % "#FF0000"
    "#0F62FE"
    % "#0F62FE"
    "#24A249"
    % "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "southeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.7 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 2
profile_name = "Human, R/H - 5/10s Windows, %-based, rho>=0.9";
p = struct;
p.primary_var = "frequency_limit";
p.primary_vals = [];
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', []);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 10, ...
    'frequency_limit', 30, ...
    'training_type', "percentage", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0.9, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'window_duration', 10)
    struct('signal_sel', "raw_signal", 'window_duration', 5)
    struct('signal_sel', "IPFM_signal", 'window_duration', 10)
    struct('signal_sel', "IPFM_signal", 'window_duration', 5)
    struct('signal_sel', "EHR_signal", 'window_duration', 10)
    struct('signal_sel', "EHR_signal", 'window_duration', 5)
    };
p.legend_vec = {
    "Raw PVP, 10s windows"
    "Raw PVP, 5s windows"
    "IPFM-PVP, 10s windows"
    "IPFM-PVP, 5s windows"
    "IPFM-HB, 10s windows"
    "IPFM-HB, 5s windows"
    };
p.line_styles = {
    "-o"
    "--o"
    "-x"
    "--x"
    "-v"
    "--v"
    };
p.line_colors = {
    "#FF0000"
    "#FF0000"
    "#0F62FE"
    "#0F62FE"
    "#24A249"
    "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "southeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.7 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 3
profile_name = "Human, R/H - 5/10s Windows, P-based, rho>=0.9";
p = struct;
p.primary_var = "frequency_limit";
p.primary_vals = [];
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', []);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 10, ...
    'frequency_limit', 30, ...
    'training_type', "patient", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0.9, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'window_duration', 10)
    struct('signal_sel', "IPFM_signal", 'window_duration', 10)
    struct('signal_sel', "EHR_signal", 'window_duration', 10)
    };
p.legend_vec = {
    "Raw PVP, 10s windows"
    "IPFM-PVP, 10s windows"
    "IPFM-HB, 10s windows"
    };
p.line_styles = {
    "-o"
    "-x"
    "-v"
    };
p.line_colors = {
    "#FF0000"
    "#0F62FE"
    "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "southeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.7 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 4
profile_name = "Human, R/H - 5/10s Windows, %-based";
p = struct;
p.primary_var = "frequency_limit";
p.primary_vals = [];
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', [31]);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 10, ...
    'frequency_limit', 30, ...
    'training_type', "percentage", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'window_duration', 10)
    struct('signal_sel', "raw_signal", 'window_duration', 5)
    struct('signal_sel', "IPFM_signal", 'window_duration', 10)
    struct('signal_sel', "IPFM_signal", 'window_duration', 5)
    struct('signal_sel', "EHR_signal", 'window_duration', 10)
    struct('signal_sel', "EHR_signal", 'window_duration', 5)
    };
p.legend_vec = {
    "Raw PVP, 10s windows"
    "Raw PVP, 5s windows"
    "IPFM-PVP, 10s windows"
    "IPFM-PVP, 5s windows"
    "IPFM-HB, 10s windows"
    "IPFM-HB, 5s windows"
    };
p.line_styles = {
    "-o"
    "--o"
    "-x"
    "--x"
    "-v"
    "--v"
    };
p.line_colors = {
    "#FF0000"
    "#FF0000"
    "#0F62FE"
    "#0F62FE"
    "#24A249"
    "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "southeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.6 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 5
profile_name = "Human, R/H - 5/10s Windows, P-based";
p = struct;
p.primary_var = "frequency_limit";
p.primary_vals = [];
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', [31]);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 10, ...
    'frequency_limit', 30, ...
    'training_type', "patient", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'window_duration', 10)
    struct('signal_sel', "raw_signal", 'window_duration', 5)
    struct('signal_sel', "IPFM_signal", 'window_duration', 10)
    struct('signal_sel', "IPFM_signal", 'window_duration', 5)
    struct('signal_sel', "EHR_signal", 'window_duration', 10)
    struct('signal_sel', "EHR_signal", 'window_duration', 5)
    };
p.legend_vec = {
    "Raw PVP, 10s wins."
    "Raw PVP, 5s wins."
    "IPFM-PVP, 10s wins."
    "IPFM-PVP, 5s wins."
    "IPFM-HB, 10s wins."
    "IPFM-HB, 5s wins."
    };
p.line_styles = {
    "-o"
    "--o"
    "-x"
    "--x"
    "-v"
    "--v"
    };
p.line_colors = {
    "#FF0000"
    "#FF0000"
    "#0F62FE"
    "#0F62FE"
    "#24A249"
    "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "northeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.65 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 6
profile_name = "Human, R/H - Rho sweep";
p = struct;
p.primary_var = "drop_rho_below";
p.primary_vals = 0.4:0.1:0.9;
p.data_defaults = struct(...
    'dataset', "Human", ...
    'signal_sel', "raw_signal", ...
    'labels', struct("bolus_type", "BB", ...
    "hypovolemic", "R"), ...
    'exclude_patients', []);
p.data_groups = {
    struct("hypovolemic", "R")
    struct("hypovolemic", "H")
    };
p.model_settings = struct(...
    'model_type', "lrm",...
    'alpha', 0.5,...
    'cv_spec', 5,...
    'max_iterations', 1e8);
p.model_parameters = struct(...
    'window_duration', 5, ...
    'frequency_limit', 5, ...
    'training_type', "percentage", ...
    'training_percentage', 0.7,...
    'randomize_training',false,...
    'split_by', "signal", ...
    'tshift', 1, ...
    'drop_rho_below', 0.9, ...
    'drop_DC_component', true, ...
    'normalize_power', true,...
    'pca_method', "none",...
    'pca_sigma_threshold', 0,...
    'fft_type',"mag",...
    'log1p_regularization', false,...
    'data_centering', false);
p.line_configs = {
    struct('signal_sel', "raw_signal", 'window_duration', 10)
    struct('signal_sel', "raw_signal", 'window_duration', 5)
    struct('signal_sel', "IPFM_signal", 'window_duration', 10)
    struct('signal_sel', "IPFM_signal", 'window_duration', 5)
    struct('signal_sel', "EHR_signal", 'window_duration', 10)
    struct('signal_sel', "EHR_signal", 'window_duration', 5)
    };
p.legend_vec = {
    "Raw PVP, 10s windows"
    "Raw PVP, 5s windows"
    "IPFM-PVP, 10s windows"
    "IPFM-PVP, 5s windows"
    "IPFM-HB, 10s windows"
    "IPFM-HB, 5s windows"
    };
p.line_styles = {
    "-o"
    "--o"
    "-x"
    "--x"
    "-v"
    "--v"
    };
p.line_colors = {
    "#FF0000"
    "#FF0000"
    "#0F62FE"
    "#0F62FE"
    "#24A249"
    "#24A249"
    };
p.delete_configs = [];
p.legend_loc = "southeast";
p.xlim_vec = [0 0.3];
p.ylim_vec = [0.5 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];